settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: crontab
    path: ./
    commands:
      vet:
        status: true
      install:
        status: true
        method: go build -o ./crontab
      run:
        status: true
        method: ./crontab
        args: -config=./setting.ini -ext=./setting_ext.ini
    watcher:
      extensions:
        - go
      paths:
        - ./src
      ignored_paths:
        - .git
        - .realize
        - vendor
